// This file is a placeholder. 
// Normally, this file is generated by the FlutterFire CLI.
// Since I cannot run terminal commands, I am creating this stub 
// so you can compile the code. 

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: You must replace these with your actual Firebase project keys

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSa--7z58XRb2k9Sgsy8u_Qeq65tGjIro',
    appId: '1:917808259940:android:3ed16322413da251d0d071',
    messagingSenderId: '917808259940',
    projectId: 'subudget-a8a79',
    storageBucket: 'subudget-a8a79.firebasestorage.app',
  );

  // obtained from the Firebase Console or by running 'flutterfire configure'

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-PROJECT-ID.appspot.com',
    iosBundleId: 'com.example.budgetSu',
  );
}